apiVersion: gitops.kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres-v
  namespace: ping
spec:
  replicas: 3
  version: "16.6"
  storageType: Durable
  podTemplate:
    spec:
      containers:
      - name: postgres
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 700m
            memory: 1.7Gi
      # - name: exporter
      #   resources: 
      #     limits: 
      #       memory: 1.5Gi
      #     requests:
      #       cpu: 700m
      #       memory: 2Gi
  storage:
    storageClassName: "longhorn"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  deletionPolicy: WipeOut